sonata_admin:
    title: 'Test Sonata'
    title_logo: /medias/images/logo.jpg
    dashboard:
        blocks:
            - { type: sonata.admin.block.admin_list, position: left }
    templates:
        # default global templates
        layout: '@SonataAdmin/standard_layout.html.twig'
    assets:
        extra_stylesheets:
        - bundles/sonatatranslation/css/sonata-translation.css

sonata_block:
    blocks:
        sonata.admin.block.admin_list:
            contexts: [admin]
        sonata_translation.block.locale_switcher: null
